import './globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { getCookie, PRODUCTS_IN_CART_COOKIE_NAME } from '../util/cookies';
import { parseJson } from '../util/json';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { default: 'Home | HG', template: '%s | HG' },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const productsQuantitysCookie = getCookie(PRODUCTS_IN_CART_COOKIE_NAME);
  const productsInCart = !productsQuantitysCookie
    ? []
    : parseJson(productsQuantitysCookie);

  const initialValue = 0;
  const totalQuantity = productsInCart.reduce((previousValue, product) => {
    return previousValue + product.quantity;
  }, initialValue);

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div>
            <Link href="/">Home</Link>
            <Link href="http://localhost:3000/products">Products</Link>
            <Link href="/cart">Cart</Link>
            <Link href="/checkout">Checkout</Link>
            <Link href="/thankyou">Thank You!</Link>
          </div>
          {totalQuantity} products in 🛒
        </nav>
        {children}
      </body>
    </html>
  );
}
