import './globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { default: 'Home | HG', template: '%s | HG' },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div>
            <Link href="/">Home</Link>
            <Link href="http://localhost:3000/products">Products</Link>
            <Link href="/cart">Cart</Link>
            <Link href="/checkout">Checkout</Link>
            <Link href="/thankyou">Thank You!</Link>
            <Link href="/about">About</Link>
          </div>
          {Math.floor(Math.random() * 10)}
        </nav>
        {children}
      </body>
    </html>
  );
}
